# Generated by Django 3.0.4 on 2020-04-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_log_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
